apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-crossplane-config-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-crossplane-config-read-credentials
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-crossplane-config-read-credentials-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-crossplane-config-read-credentials
subjects:
- kind: ServiceAccount
  name: vault-crossplane-config-sa