argo-cd:
  crds:
    keep: true
  configs:
    params:
      server.insecure: "true"
  server:
    url: https://__ARGOCD_HOSTNAME__
    ingress:
      enabled: true
      controller: generic
      ingressClassName: nginx
      hostname: __ARGOCD_HOSTNAME__
      path: /
      pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: lab-ca-issuer
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/hsts: "true"
      tls: false
      extraTls:
        - hosts:
            - __ARGOCD_HOSTNAME__
          secretName: argocd-server-tls-secret
